# Generated by Django 4.2.1 on 2023-05-06 12:35

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('types', models.CharField(choices=[('government', 'Government'), ('public', 'Public Facility'), ('park', 'Park'), ('cafe', 'Cafe'), ('restaurant', 'Restaurant'), ('parking', 'Parking Lot'), ('finance', 'Financial Service'), ('cinema', 'Cinema'), ('amusement', 'Amusement'), ('shop', 'Shop'), ('market', 'Market'), ('worship', 'Worship Place'), ('homestay', 'Homestay'), ('hotel', 'Hotel'), ('house', 'House'), ('apartment', 'Apartment'), ('office', 'Office')], max_length=10)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('constructing', 'Under Construction'), ('open', 'Service is open'), ('close', 'Service is closed')], max_length=12)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_unit', models.CharField(choices=[('hour', 'Hourly'), ('hour_3', 'Per 3 hours'), ('hour_6', 'Per 6 hours'), ('hour_12', 'Per 12 hours'), ('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly'), ('year', 'Annual')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
            },
        ),
    ]
