# Generated by Django 4.2.1 on 2023-05-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='price_unit',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('per 3 hours', 'Per 3 hours'), ('per 6 hours', 'Per 6 hours'), ('per 12 hours', 'Per 12 hours'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], max_length=12),
        ),
    ]
