# Generated by Django 4.2.1 on 2023-05-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0012_alter_facility_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facility',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('under review', 'Under Review'), ('planned', 'Planned'), ('cancelled', 'Cancelled'), ('constructing', 'Under Construction'), ('complete', 'Completed')], max_length=12),
        ),
    ]
