# Generated by Django 4.2.1 on 2023-05-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0015_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('under review', 'Under Review'), ('planned', 'Planned'), ('cancelled', 'Cancelled'), ('constructing', 'Under Construction'), ('complete', 'Completed')], default='proposed', max_length=12),
        ),
    ]
