# Generated by Django 4.2.1 on 2023-05-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0016_alter_facility_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineinfrastructure',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('under review', 'Under Review'), ('planned', 'Planned'), ('cancelled', 'Cancelled'), ('constructing', 'Under Construction'), ('complete', 'Completed')], max_length=12),
        ),
    ]
