# Generated by Django 4.2.1 on 2023-05-10 18:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0018_alter_complaint_status_handling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='specific_location',
            field=django.contrib.gis.db.models.fields.PointField(default='SRID=4326;POINT(11.60 165.39)', srid=4326),
        ),
    ]
