# Generated by Django 4.2.1 on 2023-05-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0025_alter_complaint_specific_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_recommended',
        ),
    ]
