# Generated by Django 4.2.1 on 2023-05-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0027_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('refund', 'Refund')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='types',
            field=models.CharField(choices=[('inactive', 'Inactive Service'), ('damage', 'Infrastructure Damage'), ('malfunction', 'Malfunction Service'), ('vandalism', 'Vandalism'), ('crime', 'Crime')], max_length=12),
        ),
        migrations.AlterField(
            model_name='facility',
            name='price_unit',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('per 3 hours', 'Per 3 hours'), ('per 6 hours', 'Per 6 hours'), ('per 12 hours', 'Per 12 hours'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual'), ('pcs', 'Pcs'), ('g', 'Gram'), ('kg', 'Kilogram')], max_length=12),
        ),
    ]
