# Generated by Django 4.2.1 on 2023-05-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0028_alter_booking_payment_status_alter_complaint_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('cancel', 'Cancelled'), ('refund', 'Refund'), ('no refund', 'No Refund')], default='unpaid', max_length=10),
        ),
    ]
