# Generated by Django 4.2.1 on 2023-05-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0029_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('cancel', 'Cancelled'), ('refund', 'Refund'), ('no refund', 'No Refund'), ('invalid', 'Invalid')], default='unpaid', max_length=10),
        ),
    ]
